name: 'assignment3'
version: '1.0.0'
config-version: 2

profile: 'assignment3'

model-paths: ["models"]
analysis-paths: ["analyses"]
test-paths: ["tests"]
seed-paths: ["seeds"]
macro-paths: ["macros"]
snapshot-paths: ["snapshots"]

target-path: "target" 
clean-targets:  
  - "target"
  - "dbt_packages"


models:
  assignment3:
      bronze:
          +schema: bronze
          +materialized: table

      silver:
          +schema: silver
          +materialized: table
      gold:
          dimension:
            +schema: gold
            +materialized: table
          fact: 
            +schema: gold
            +materialized: table  
          mart:
            +schema: gold
            +materialized: view 

snapshots:
      +schema: silver
      +materialized: snapshot