version: 2
sources:
  - name: raw
    description: Raw data from CSV files
    database: postgres
    schema: bronze

    tables:
      - name: lga_code
        description: "Raw data containing Local Government Area codes"
      - name: lga_suburb
        description: "Raw data containing Local Government Area suburb mappings"
      - name: census_g01
        description: "Raw Census data - G01 table"
      - name: census_g02
        description: "Raw Census data - G02 table"
      - name: airbnb_listings
        description: "Raw data of Airbnb listings"