version: 2
sources:
  - name: raw
    description: Raw data from CSV files
    database: postgres
    schema: bronze

    tables:
      - name: lga_code
      - name: lga_suburb
      - name: census_g01
      - name: census_g02
      - name: airbnb_listings